// atlas-richie-gateway-service/src/main/resources/client-library/web/examples/vue/components/LoginForm.vue
<!--
  Vue登录表单组件
  
  @author richie696
  @version 1.0
  @since 2025-11-01
-->

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../composables/useAuth';

const router = useRouter();
const { login, loading, error } = useAuth();

const username = ref('');
const password = ref('');

const handleSubmit = async () => {
    try {
        await login(username.value, password.value);
        console.log('登录成功');
        router.push('/dashboard');
    } catch (err) {
        console.error('登录失败:', err);
    }
};
</script>

<template>
    <div class="login-form">
        <h2>用户登录</h2>

        <form @submit.prevent="handleSubmit">
            <div class="form-group">
                <label for="username">用户名</label>
                <input
                    id="username"
                    v-model="username"
                    type="text"
                    placeholder="请输入用户名"
                    :disabled="loading"
                    required
                />
            </div>

            <div class="form-group">
                <label for="password">密码</label>
                <input
                    id="password"
                    v-model="password"
                    type="password"
                    placeholder="请输入密码"
                    :disabled="loading"
                    required
                />
            </div>

            <div v-if="error" class="error-message">
                {{ error }}
            </div>

            <button type="submit" :disabled="loading">
                {{ loading ? '登录中...' : '登录' }}
            </button>
        </form>
    </div>
</template>

<style scoped>
.login-form {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
}

.form-group {
    margin-bottom: 15px;
}

label {
    display: block;
    margin-bottom: 5px;
}

input {
    width: 100%;
    padding: 8px;
    border: 1px solid #ddd;
    border-radius: 4px;
}

button {
    width: 100%;
    padding: 10px;
    background-color: #42b983;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

button:disabled {
    background-color: #ccc;
    cursor: not-allowed;
}

.error-message {
    color: #f56c6c;
    margin-bottom: 10px;
}
</style>

// atlas-richie-gateway-service/src/main/resources/client-library/web/examples/react/components/LoginForm.tsx
/**
 * React登录表单组件
 * 
 * @author richie696
 * @version 1.0
 * @since 2025-11-01
 */

import React, { useState } from 'react';
import { useAuth } from '../hooks/useAuth';

// 定义用户数据类型（示例）
interface User {
    userId: string;
    username: string;
    email: string;
}

/**
 * 登录表单组件
 * 演示如何使用useAuth Hook进行登录
 */
export function LoginForm() {
    const { login, loading, error } = useAuth<User>();
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        
        try {
            await login(username, password);
            console.log('登录成功');
            // 跳转到首页
            window.location.href = '/dashboard';
        } catch (err) {
            console.error('登录失败:', err);
        }
    };

    return (
        <form onSubmit={handleSubmit} className="login-form">
            <h2>用户登录</h2>
            
            <div className="form-group">
                <label htmlFor="username">用户名</label>
                <input
                    id="username"
                    type="text"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    placeholder="请输入用户名"
                    disabled={loading}
                    required
                />
            </div>

            <div className="form-group">
                <label htmlFor="password">密码</label>
                <input
                    id="password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="请输入密码"
                    disabled={loading}
                    required
                />
            </div>

            {error && (
                <div className="error-message">
                    {error}
                </div>
            )}

            <button type="submit" disabled={loading}>
                {loading ? '登录中...' : '登录'}
            </button>
        </form>
    );
}

export default LoginForm;
